# Generated by Django 5.2.17 on 2026-09-19 08:14

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.PositiveIntegerField(default=49000, verbose_name='هزینه ارسال (تومان)')),
                ('reservation_minutes', models.PositiveIntegerField(default=20, help_text='بعد از ثبتِ سفارش (پر کردنِ فرمِ checkout)، موجودیِ کالاها بلافاصله کم می\u200cشود. اگر مشتری تا این تعداد دقیقه پرداخت نکند، سفارش خودکار لغو و موجودی برگردانده می\u200cشود.', verbose_name='مدت\u200cزمان رزرو موجودی (دقیقه)')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات سفارش و ارسال',
                'verbose_name_plural': 'تنظیمات سفارش و ارسال',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل داده\u200cشده'), ('cancelled', 'لغوشده')], default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('courier', models.CharField(blank=True, choices=[('tipax', 'تیپاکس'), ('iran_post', 'پست ایران')], help_text='بعد از تحویلِ مرسوله به باربری پر کنید — همراه با کدِ رهگیریِ زیر، دکمه\u200cی «پیگیری مرسوله» را در صفحه\u200cی سفارشِ مشتری فعال می\u200cکند.', max_length=20, verbose_name='شرکت باربری')),
                ('courier_tracking_code', models.CharField(blank=True, help_text='کدی که خودِ باربری (نه سایتِ ما) هنگام تحویل\u200cگرفتنِ مرسوله می\u200cدهد. مشتری همین کد را در سایتِ باربری وارد می\u200cکند تا وضعیتِ لحظه\u200cای مرسوله را ببیند.', max_length=64, verbose_name='کدِ رهگیریِ باربری')),
                ('tracking_code', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='کد رهگیری')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('national_code', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('full_address', models.TextField(verbose_name='آدرس کامل پستی')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت اینترنتی')], default='online', max_length=20, verbose_name='روش پرداخت')),
                ('subtotal_price', models.PositiveIntegerField(verbose_name='جمع قیمت محصولات')),
                ('product_discount_amount', models.PositiveIntegerField(default=0, verbose_name='تخفیف محصولات')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='تخفیف کد تخفیف/کمپین')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی قابل پرداخت')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('variant_label', models.CharField(max_length=100, verbose_name='برچسب وزن/سروینگ')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
