# Generated by Django 5.2.17 on 2026-09-13 08:34

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.PositiveIntegerField(default=49000, verbose_name='هزینه ارسال (تومان)')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'هزینه ارسال',
                'verbose_name_plural': 'هزینه ارسال',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف محصولات'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف کد تخفیف/کمپین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plaque',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک'),
        ),
    ]
