# Generated by Django 5.2.17 on 2026-09-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plaque',
        ),
        migrations.AddField(
            model_name='order',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
