# Generated by Django 5.2.17 on 2026-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_full_address_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='full_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='building_number',
        ),
        migrations.AddField(
            model_name='order',
            name='plaque',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف محصولات'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف کد تخفیف/کمپین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
