# Generated by Django 5.2.17 on 2026-09-10 06:32

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_address_order_full_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.PositiveIntegerField(default=49000, verbose_name='هزینه ارسال (تومان)')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'هزینه ارسال',
                'verbose_name_plural': 'هزینه ارسال',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plaque',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='order',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
