# Generated by Django 5.2.17 on 2026-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_address_order_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, choices=[('tipax', 'تیپاکس'), ('iran_post', 'پست ایران')], help_text='بعد از تحویلِ مرسوله به باربری پر کنید — همراه با کدِ رهگیریِ زیر، دکمه\u200cی «پیگیری مرسوله» را در صفحه\u200cی سفارشِ مشتری فعال می\u200cکند.', max_length=20, verbose_name='شرکت باربری'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_tracking_code',
            field=models.CharField(blank=True, help_text='کدی که خودِ باربری (نه سایتِ ما) هنگام تحویل\u200cگرفتنِ مرسوله می\u200cدهد. مشتری همین کد را در سایتِ باربری وارد می\u200cکند تا وضعیتِ لحظه\u200cای مرسوله را ببیند.', max_length=64, verbose_name='کدِ رهگیریِ باربری'),
        ),
    ]
