# Generated by Django 5.2.17 on 2026-09-19 08:14

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام طعم')),
            ],
            options={
                'verbose_name': 'طعم',
                'verbose_name_plural': 'طعم\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, help_text='در کارت\u200cهای دسته\u200cبندی صفحه\u200cی اصلی نمایش داده می\u200cشود', null=True, upload_to='categories/', verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_main_category', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='فقط دسته\u200cبندی\u200cهای بدون والد قابل انتخاب به\u200cعنوان دسته\u200cبندی اصلی هستند.', verbose_name='دسته\u200cبندی اصلی')),
                ('is_popular', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='حداکثر ۸ دسته\u200cبندی محبوب در صفحه\u200cی اصلی نمایش داده می\u200cشود؛ فقط برای دسته\u200cبندی\u200cهای اصلی قابل انتخاب است.', verbose_name='دسته\u200cبندی محبوب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(blank=True, help_text='در کارت محصولات نمایش داده می\u200cشود', max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='نحوه مصرف')),
                ('form_type', models.CharField(blank=True, choices=[('powder', 'پودر'), ('tablets', 'قرص / کپسول'), ('liquid', 'مایع / شات')], help_text='برای فیلتر «نوع مکمل» در صفحه\u200cی محصولات استفاده می\u200cشود', max_length=20, verbose_name='نوع/فرم مکمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (قابل نمایش)')),
                ('is_best_seller', models.BooleanField(default=False, help_text='در صفحه\u200cی اصلی، بخش «محصولات پرفروش» را همین\u200cها (حداکثر ۸ تا) پر می\u200cکنند.', verbose_name='پرفروش')),
                ('is_featured_deal', models.BooleanField(default=False, help_text='در صفحه\u200cی اصلی، بخش «تخفیفات ویژه و شگفت\u200cانگیز» را همین\u200cها (حداکثر ۸ تا) پر می\u200cکنند.', verbose_name='تخفیف ویژه/شگفت\u200cانگیز')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: ۲۲۷۰ گرم (۷۴ سروینگ)', max_length=100, verbose_name='برچسب وزن/سروینگ')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن (گرم)')),
                ('servings_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد سروینگ')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد کالا (SKU)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('compare_at_price', models.PositiveIntegerField(blank=True, help_text='خالی بگذارید اگر تخفیف ندارد', null=True, verbose_name='قیمت قبل از تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('flavor', models.ForeignKey(blank=True, help_text='برای محصولاتی مثل کپسول که طعم ندارند خالی بگذارید', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.flavor', verbose_name='طعم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول (Variant)',
                'verbose_name_plural': 'تنوع\u200cهای محصول (Variants)',
                'ordering': ['price'],
            },
        ),
    ]
