# Generated by Django 5.2.17 on 2026-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='در کارت دسته\u200cبندی صفحه\u200cی اصلی نمایش داده می\u200cشود', null=True, upload_to='categories/', verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='product',
            name='form_type',
            field=models.CharField(blank=True, choices=[('powder', 'پودر'), ('tablets', 'قرص / کپسول'), ('liquid', 'مایع / شات')], help_text='برای فیلتر «نوع مکمل» در صفحه\u200cی محصولات استفاده می\u200cشود', max_length=20, verbose_name='نوع/فرم مکمل'),
        ),
    ]
