# Generated by Django 5.2.17 on 2026-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon_product_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='در کارت\u200cهای دسته\u200cبندی صفحه\u200cی اصلی نمایش داده می\u200cشود', null=True, upload_to='categories/', verbose_name='آیکون'),
        ),
    ]
