# Generated by Django 5.2.17 on 2026-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main_category',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='فقط دسته\u200cبندی\u200cهای بدون والد قابل انتخاب به\u200cعنوان دسته\u200cبندی اصلی هستند.', verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='حداکثر ۸ دسته\u200cبندی محبوب در صفحه\u200cی اصلی نمایش داده می\u200cشود؛ فقط برای دسته\u200cبندی\u200cهای اصلی قابل انتخاب است.', verbose_name='دسته\u200cبندی محبوب'),
        ),
    ]
