# Generated by Django 5.2.17 on 2026-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_is_main_category_category_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='در صفحه\u200cی اصلی، بخش «محصولات پرفروش» را همین\u200cها (حداکثر ۸ تا) پر می\u200cکنند.', verbose_name='پرفروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured_deal',
            field=models.BooleanField(default=False, help_text='در صفحه\u200cی اصلی، بخش «تخفیفات ویژه و شگفت\u200cانگیز» را همین\u200cها (حداکثر ۸ تا) پر می\u200cکنند.', verbose_name='تخفیف ویژه/شگفت\u200cانگیز'),
        ),
    ]
