# Generated by Django 5.2.17 on 2026-09-19 08:14

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(choices=[('support', 'پشتیبانی و پیگیری سفارش'), ('consult', 'مشاوره خرید مکمل'), ('complaint', 'انتقاد یا شکایت'), ('cooperation', 'همکاری و مشاوره تجاری')], max_length=20, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role_label', models.CharField(blank=True, help_text='مثال: "خریدار وی پروتئین"', max_length=100, verbose_name='برچسب (اختیاری)')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('display_date', models.CharField(blank=True, help_text='مثال: "تیر ۱۴۰۵" — متن آزاد، برای نمایش', max_length=50, verbose_name='تاریخ نمایشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نظر مشتری (صفحه درباره ما)',
                'verbose_name_plural': 'نظرات مشتریان (صفحه درباره ما)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', models.ImageField(blank=True, help_text='همین یک تصویر هم به\u200cجای لوگوی هدر/فوتر سایت و هم به\u200cعنوان فاویکونِ تبِ مرورگر استفاده می\u200cشود. ترجیحاً یک تصویرِ مربعیِ ساده (بدونِ متنِ ریز که در اندازه\u200cی کوچکِ فاویکون ناخوانا می\u200cشود).', null=True, upload_to='branding/', verbose_name='لوگو / برند سایت')),
                ('terms_text', models.TextField(blank=True, default='با ثبت سفارش در بانک مکمل، تأیید می\u200cنمایم که مشخصات و اطلاعات مربوط به محصول، از جمله ترکیبات، نحوه مصرف، شرایط نگهداری، هشدارها و محدودیت\u200cهای مربوط به آن را مطالعه کرده و با آگاهی از اطلاعات ارائه\u200cشده، اقدام به خرید می\u200cنمایم.\n\nهمچنین متعهد می\u200cشوم محصولات خریداری\u200cشده را مطابق دستورالعمل و اطلاعات درج\u200cشده بر روی محصول و توضیحات ارائه\u200cشده در بانک مکمل مورد استفاده قرار دهم.\n\nثبت سفارش در بانک مکمل به منزله مطالعه و پذیرش شرایط و قوانین استفاده از سایت، شرایط خرید و پرداخت، نحوه ارسال، شرایط مرجوعی و خدمات پس از فروش می\u200cباشد.', help_text='در مودالِ «شرایط و قوانین» صفحه\u200cی ورود/ثبت\u200cنام نمایش داده می\u200cشود. هر پاراگراف را با یک خط خالی از پاراگرافِ بعدی جدا کنید.', verbose_name='متن شرایط و قوانین')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو')),
                ('hero_subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان هیرو')),
                ('hero_description', models.TextField(blank=True, verbose_name='توضیح هیرو')),
                ('site_description', models.TextField(blank=True, help_text='در فوتر و بخش\u200cهای معرفی نمایش داده می\u200cشود', verbose_name='توضیح کوتاه درباره\u200cی فروشگاه')),
                ('about_hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو صفحه\u200cی درباره ما')),
                ('about_hero_description', models.TextField(blank=True, verbose_name='توضیح هیرو صفحه\u200cی درباره ما')),
                ('about_page_content', models.TextField(blank=True, help_text='در صورت پر بودن، زیر بخش آمار نمایش داده می\u200cشود. هر پاراگراف را با یک خط خالی جدا کنید.', verbose_name='متن تکمیلی صفحه\u200cی درباره ما (اختیاری)')),
                ('stat1_number', models.CharField(blank=True, max_length=30, verbose_name='آمار ۱ - عدد')),
                ('stat1_label', models.CharField(blank=True, max_length=50, verbose_name='آمار ۱ - برچسب')),
                ('stat2_number', models.CharField(blank=True, max_length=30, verbose_name='آمار ۲ - عدد')),
                ('stat2_label', models.CharField(blank=True, max_length=50, verbose_name='آمار ۲ - برچسب')),
                ('stat3_number', models.CharField(blank=True, max_length=30, verbose_name='آمار ۳ - عدد')),
                ('stat3_label', models.CharField(blank=True, max_length=50, verbose_name='آمار ۳ - برچسب')),
                ('stat4_number', models.CharField(blank=True, max_length=30, verbose_name='آمار ۴ - عدد')),
                ('stat4_label', models.CharField(blank=True, max_length=50, verbose_name='آمار ۴ - برچسب')),
                ('contact_hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو صفحه\u200cی تماس با ما')),
                ('contact_hero_description', models.TextField(blank=True, verbose_name='توضیح هیرو صفحه\u200cی تماس با ما')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('phones', models.TextField(blank=True, help_text='هر شماره را در یک خط جداگانه وارد کنید', verbose_name='شماره\u200cهای تماس')),
                ('emails', models.TextField(blank=True, help_text='هر ایمیل را در یک خط جداگانه وارد کنید', verbose_name='ایمیل\u200cها')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات پاسخگویی')),
                ('instagram_url', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, verbose_name='لینک تلگرام')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='لینک واتساپ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('hero_product', models.ForeignKey(blank=True, help_text='محصولی که در کارت سمت راست هیروی صفحه\u200cی اصلی نمایش داده می\u200cشود. اگر خالی بماند یا محصول انتخاب\u200cشده غیرفعال/بدون تنوع فعال باشد، به\u200cطور خودکار جدیدترین محصول فعال جایگزین می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='محصول ویژه\u200cی هیرو')),
            ],
            options={
                'verbose_name': 'تنظیمات محتوای سایت',
                'verbose_name_plural': 'تنظیمات محتوای سایت',
            },
        ),
    ]
