# Generated by Django 5.2.17 on 2026-09-03 07:48

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو')),
                ('hero_subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان هیرو')),
                ('hero_description', models.TextField(blank=True, verbose_name='توضیح هیرو')),
                ('site_description', models.TextField(blank=True, help_text='در فوتر و بخش\u200cهای معرفی نمایش داده می\u200cشود', verbose_name='توضیح کوتاه درباره\u200cی فروشگاه')),
                ('about_page_content', models.TextField(blank=True, help_text='هر پاراگراف را با یک خط خالی از پاراگراف بعدی جدا کنید', verbose_name='محتوای کامل صفحه\u200cی درباره ما')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس پشتیبانی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات پاسخگویی')),
                ('instagram_url', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, verbose_name='لینک تلگرام')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='لینک واتساپ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات محتوای سایت',
                'verbose_name_plural': 'تنظیمات محتوای سایت',
            },
        ),
    ]