# Generated by Django 5.2.17 on 2026-09-07 06:11

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(choices=[('support', 'پشتیبانی و پیگیری سفارش'), ('consult', 'مشاوره خرید مکمل'), ('complaint', 'انتقاد یا شکایت'), ('cooperation', 'همکاری و مشاوره تجاری')], max_length=20, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role_label', models.CharField(blank=True, help_text='مثال: "خریدار وی پروتئین"', max_length=100, verbose_name='برچسب (اختیاری)')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('display_date', models.CharField(blank=True, help_text='مثال: "تیر ۱۴۰۵" — متن آزاد، برای نمایش', max_length=50, verbose_name='تاریخ نمایشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نظر مشتری (صفحه درباره ما)',
                'verbose_name_plural': 'نظرات مشتریان (صفحه درباره ما)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_description',
            field=models.TextField(blank=True, verbose_name='توضیح هیرو صفحه\u200cی درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو صفحه\u200cی درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_description',
            field=models.TextField(blank=True, verbose_name='توضیح هیرو صفحه\u200cی تماس با ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان هیرو صفحه\u200cی تماس با ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emails',
            field=models.TextField(blank=True, help_text='هر ایمیل را در یک خط جداگانه وارد کنید', verbose_name='ایمیل\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phones',
            field=models.TextField(blank=True, help_text='هر شماره را در یک خط جداگانه وارد کنید', verbose_name='شماره\u200cهای تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='آمار ۱ - برچسب'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='آمار ۱ - عدد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='آمار ۲ - برچسب'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='آمار ۲ - عدد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='آمار ۳ - برچسب'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='آمار ۳ - عدد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat4_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='آمار ۴ - برچسب'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat4_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='آمار ۴ - عدد'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_page_content',
            field=models.TextField(blank=True, help_text='در صورت پر بودن، زیر بخش آمار نمایش داده می\u200cشود. هر پاراگراف را با یک خط خالی جدا کنید.', verbose_name='متن تکمیلی صفحه\u200cی درباره ما (اختیاری)'),
        ),
    ]
