# Generated by Django 5.2.17 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactmessage_testimonial_remove_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='express_shipping_cost',
            field=models.PositiveIntegerField(default=49000, help_text='این مبلغ در صفحه\u200cی تسویه\u200cحساب به\u200cعنوان هزینه\u200cی ارسال به مشتری نمایش داده می\u200cشود.', verbose_name='هزینه ارسال اکسپرس (تومان)'),
        ),
    ]
