# Generated by Django 5.2.17 on 2026-09-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sitesettings_express_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='express_shipping_cost',
        ),
    ]
