# Generated by Django 5.2.17 on 2026-09-12 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_icon'),
        ('store', '0004_remove_sitesettings_express_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_product',
            field=models.ForeignKey(blank=True, help_text='محصولی که در کارت سمت راست هیروی صفحه\u200cی اصلی نمایش داده می\u200cشود. اگر خالی بماند یا محصول انتخاب\u200cشده غیرفعال/بدون تنوع فعال باشد، به\u200cطور خودکار جدیدترین محصول فعال جایگزین می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='محصول ویژه\u200cی هیرو'),
        ),
    ]
