# Generated by Django 5.2.17 on 2026-09-13 12:38

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً «خانه» یا «محل کار»', max_length=50, verbose_name='عنوان آدرس')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی تحویل\u200cگیرنده')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('full_address', models.TextField(verbose_name='آدرس کامل پستی')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
