# Generated by Django 5.2.17 on 2026-09-12 05:14

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_rename_address_order_full_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(help_text='برای نوع «درصدی» عددی بین ۱ تا ۱۰۰؛ برای نوع «مبلغ ثابت» مبلغ به تومان.', verbose_name='مقدار تخفیف')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, help_text='فقط برای نوع «درصدی» — تخفیف محاسبه\u200cشده هیچ\u200cوقت از این مبلغ بیشتر نمی\u200cشود. برای «مبلغ ثابت» بی\u200cاثر است.', null=True, verbose_name='سقف مبلغ تخفیف (تومان)')),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='کد فقط روی سبدهایی با قیمت محصولات حداقل به این مقدار قابل اعمال است.', verbose_name='حداقل مبلغ سبد خرید (تومان)')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='خالی بگذارید یعنی بدون محدودیت.', null=True, verbose_name='سقف تعداد کل استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد استفاده\u200cشده')),
                ('valid_from', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اعتبار')),
                ('valid_until', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupons.coupon', verbose_name='کد تخفیف')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
